#!/bin/bash

# =======================
#  HOME DIRECTORY BACKUP
# =======================

rsync -aHhv --progress \
  --exclude='Library/' \
  --exclude='.Trash/' \
  --exclude='.DS_Store' \
  --exclude='.TemporaryItems/' \
  --exclude='.DocumentRevisions-V100/' \
  --exclude='.fseventsd/' \
  --exclude='.Spotlight-V100/' \
  --exclude='.Trashes/' \
  --exclude='.cache/' \
  --exclude='.zsh_sessions/' \
  --exclude='.colima/' \ "$HOME/" /Volumes/Extended-Storage/Backups/$USER